properties:
  v1validatetoken:
    value: /sgwtv/v1/validate/token
    description: /sgwtv/v1/validate/token
    encoded: false
  Experian-URL:
    value: https://www.prod.google.com
    description: https://www.prod.google.com
  CDO-URL:
    value: https://www.prod.chatgpt.com
  dapi-appid:
    value: ijkl
    description: ijkl
  dapi-clientsecret:
    value: ijkl
    description: ijkl
  dapi-channelid:
    value: WEB
    description: WEB
  content-type:
    value: application/xml
    description: application/xml

activity-log:
  success-content: header
  error-content: header
  enabled: true

application-authentication:
  certificate: false

catalogs: {}

categories:
  - TMF/ESB/TMFGetCreditCheck

tags:
  - name: name
    description: TMFGETCreditCheck_1_0