name: Auto Update API YAML on Merge

on:
  pull_request:
    types: [closed]

jobs:
  update-api-yaml:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}


    steps:
      - name: Checkout target branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install pyyaml requests



      - name: Run main.py with source and target branches
        run: |
          echo "Source: ${{ github.event.pull_request.head.ref }}"
          echo "Target: ${{ github.event.pull_request.base.ref }}"
          python3 .github/main.py "${{ github.event.pull_request.head.ref }}" "${{ github.event.pull_request.base.ref }}"

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and Push changes
        run: |
          git add .
          git commit -m "Auto-updated api.yaml on merge" || echo "No changes to commit"
          git push
